# Generated by Django 3.0.6 on 2020-05-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200518_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='followering',
            new_name='following',
        ),
    ]
